;;; modes/+config.el -*- lexical-binding: t; -*-

(load! "+basic")
(load! "+bookmarks")
(load! "+company")
(load! "+deft")
(load! "+dired")
(load! "+emms")
(load! "elfeed-mode/+config")
(load! "+elisp")
(load! "+eshell")
(load! "+evil")
(load! "+eww")
(load! "lsp-mode/+config")
(load! "+ledger")
(load! "+magit")
(load! "+misc")
(load! "+projectile")
(load! "org-mode/+config")
(load! "+registers")
(load! "+vterm")
(load! "+winner")
