;;; modes/+config.el -*- lexical-binding: t; -*-

(load! "+basic")
(load! "+bookmarks")
(load! "+company")
(load! "+deft")
(load! "+dired")
(load! "+emms")
(load! "+elisp")
(load! "+evil")
(load! "+eww")
(load! "+magit")
(load! "+misc")
(load! "+projectile")
(load! "+registers")
(load! "+winner")
