;;; modes/elfeed-mode/+elfeed_links.el -*- lexical-binding: t; -*-

(setq elfeed-feeds
  '(
    ;; NEWSFEEDS
    ("https://9to5linux.com/feed")
    ("https://anchor.fm/s/7a32d64/podcast/rss")
    ("https://cppcast.com/episode/index.xml")
    ("https://feeds.fireside.fm/compositional/rss")
    ("https://omny.fm/shows/curiosity-daily/playlists/podcast.rss")
    ("https://feeds.twit.tv/floss.xml")
    ("https://haskellweekly.news/podcast.rss")
    ("https://itsfoss.com/rss")
    ("https://lexfridman.com/feed/podcast/")
    ("https://www.thenakedscientists.com/rss/naked_astronomy_podcast.xml")
    ("https://omgubuntu.co.uk/feed")
    ("https://rss.art19.com/planetary-radio-space-exploration-astronomy-and-science")
    ("https://omny.fm/shows/startalk-radio/playlists/podcast.rss")
    ("https://feeds.megaphone.fm/stufftoblowyourmind")
    ("https://feeds.megaphone.fm/stuffyoushouldknow")
    ("https://podcasts.files.bbci.co.uk/b00snr0w.rss")
    ("https://www.thenakedscientists.com/naked_scientists_podcast.xml")
    ("https://www.numberphile.com/podcast?format=rss")
    ("https://stackoverflow.blog/feed/")
    ("https://twimlai.com/feed")
    ("https://feeds.megaphone.fm/PP6777513342")
    ("https://anchor.fm/s/2346986c/podcast/rss")
    ("https://www.wired.com/category/science/feed")
    ("https://news.ycombinator.com/rss")

    ;; YOUTUBE
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCEJDM_70A2EiRqZ41l6bZlg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCeUJFQ0D9qs6aVNyUt9fkeQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCS0N5baNlQWJCUrhCEo8WlA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCMz9lmndR0BEqi70kM_ioyA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCvQECJukTDE2i6aCoMnS-Vg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UClIFqsmxnwVNNlsvjH1D1Aw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCl9StMQ79LtEvlrskzjoYbQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCCezIgC97PvUuR4_gbFUs5g" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCP7jMXSY2xbc3KCAE0MHQ-A" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCVls1GmFKf6WlTraIb_IaJg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCxqAWLTk1CmBvZFPzeZMd9A" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtAIs1VCQrymlAnw3mGonhw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCH4BNI0-FOK2dMXoFtViWHw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCe6ABcJkH_Gso9HJOt4x9fg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCd0dc7kQA1FUpJ76o1EjLqQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCFk__1iexL3T5gvGcMpeHNA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCwtNK3_f99g3mqS36OtoO2w" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCHaF9kM2wn8C3CLRwLkC2GQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC1_uAIS3r8Vu6JjXWvastJg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCr22xikWUK2yUW4YxOKXclQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCaiL2GDNpLYH6Wokkk1VNcg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCeiYXex_fwgYDonaTcSIk6w" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCoxcjq-8xIDTYp3uz647V5A" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCTpmmkp1E4nmZqWPS-dl5bg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCIyDqfi_cbkp-RU20aBF-MQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCR1IuLEqb6UEA_zQ81kwXfg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCK8XIGR5kRidIw2fWqwyHRA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC1yNl2E66ZzKApQdRuTQ4tw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCcN3IuIAR6Fn74FWMQf6lFA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCrMePiHCWG4Vwqv3t7W9EFg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCRDDHLvQb8HjE2r7_ZuNtWA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCnxrdFPXJMeHru_b4Q_vTPQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCvBqzzvUBLCs8Y7Axb-jZew" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC6107grRI4m0o2-emgoDnAA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCW6TXMZ5Pq6yL6_k5NZ2e0Q" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCSju5G2aFaWMqn-_0YBtq5A" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCm5mt-A4w61lknZ9lCsZtBw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCEIwxahdLz7bap-VDs9h35A" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCAiiOTio8Yu69c3XnR7nQBQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCbmNph6atAoGfqLoCL_duAg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCjSEJkpGbcZhvo0lr-44X_w" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCBsuOBu-dxj5bx1KMgmar5g" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8ENHE5xdFSwx71u3fDH5Xw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCJbPGzawDH1njbqV-D5HqKw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCQ-W1KE9EYfdxhL6S4twUNw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYeF244yNGuFefuFKqxIAXw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC0I9DSyosaahZ18SwyQbjxw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCSIvk78tK2TiviLQn4fSHaw" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UConVfxXodg78Tzh5nNu85Ew" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC9RM-iSvTu1uPJb8X5yp3EQ" youtube)
    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCftwRNsjfRo08xYE31tkiyw" youtube)

    ;; REDDIT
    ("https://www.reddit.com/r/AskComputerScience.rss" reddit)
    ("https://www.reddit.com/r/Caffe2.rss" reddit)
    ("https://www.reddit.com/r/ControlTheory.rss" reddit)
    ("https://www.reddit.com/r/DoomEmacs.rss" reddit)
    ("https://www.reddit.com/r/GraphTheory.rss" reddit)
    ("https://www.reddit.com/r/GraphicsProgramming.rss" reddit)
    ("https://www.reddit.com/r/HPC.rss" reddit)
    ("https://www.reddit.com/r/Hacking_Tutorials.rss" reddit)
    ("https://www.reddit.com/r/HowToHack.rss" reddit)
    ("https://www.reddit.com/r/Inkscape.rss" reddit)
    ("https://www.reddit.com/r/Julia.rss" reddit)
    ("https://www.reddit.com/r/Latex.rss" reddit)
    ("https://www.reddit.com/r/Learnmusic.rss" reddit)
    ("https://www.reddit.com/r/LinearAlgebra.rss" reddit)
    ("https://www.reddit.com/r/MachineLearning.rss" reddit)
    ("https://www.reddit.com/r/Musescore.rss" reddit)
    ("https://www.reddit.com/r/NextCloud.rss" reddit)
    ("https://www.reddit.com/r/Physics.rss" reddit)
    ("https://www.reddit.com/r/ProgrammerHumor.rss" reddit)
    ("https://www.reddit.com/r/Python.rss" reddit)
    ("https://www.reddit.com/r/QuantumComputing.rss" reddit)
    ("https://www.reddit.com/r/QuantumPhysics.rss" reddit)
    ("https://www.reddit.com/r/SQL.rss" reddit)
    ("https://www.reddit.com/r/TOR.rss" reddit)
    ("https://www.reddit.com/r/Ubuntu.rss" reddit)
    ("https://www.reddit.com/r/algotrading.rss" reddit)
    ("https://www.reddit.com/r/announcements.rss" reddit)
    ("https://www.reddit.com/r/artificial.rss" reddit)
    ("https://www.reddit.com/r/bash.rss" reddit)
    ("https://www.reddit.com/r/blender.rss" reddit)
    ("https://www.reddit.com/r/cmake.rss" reddit)
    ("https://www.reddit.com/r/compsci.rss" reddit)
    ("https://www.reddit.com/r/computerscience.rss" reddit)
    ("https://www.reddit.com/r/cpp.rss" reddit)
    ("https://www.reddit.com/r/cpp_questions.rss" reddit)
    ("https://www.reddit.com/r/crypto.rss" reddit)
    ("https://www.reddit.com/r/cryptography.rss" reddit)
    ("https://www.reddit.com/r/cyber_security.rss" reddit)
    ("https://www.reddit.com/r/cybersecurity.rss" reddit)
    ("https://www.reddit.com/r/datamining.rss" reddit)
    ("https://www.reddit.com/r/datascience.rss" reddit)
    ("https://www.reddit.com/r/datasets.rss" reddit)
    ("https://www.reddit.com/r/datastructures.rss" reddit)
    ("https://www.reddit.com/r/deeplearning.rss" reddit)
    ("https://www.reddit.com/r/devops.rss" reddit)
    ("https://www.reddit.com/r/docker.rss" reddit)
    ("https://www.reddit.com/r/emacs.rss" reddit)
    ("https://www.reddit.com/r/functionalprogramming.rss" reddit)
    ("https://www.reddit.com/r/geogebra.rss" reddit)
    ("https://www.reddit.com/r/git.rss" reddit)
    ("https://www.reddit.com/r/github.rss" reddit)
    ("https://www.reddit.com/r/hacking.rss" reddit)
    ("https://www.reddit.com/r/haskell.rss" reddit)
    ("https://www.reddit.com/r/haskelltil.rss" reddit)
    ("https://www.reddit.com/r/homelab.rss" reddit)
    ("https://www.reddit.com/r/learnmachinelearning.rss" reddit)
    ("https://www.reddit.com/r/learnprogramming.rss" reddit)
    ("https://www.reddit.com/r/learnpython.rss" reddit)
    ("https://www.reddit.com/r/linux.rss" reddit)
    ("https://www.reddit.com/r/linux.rss" reddit)
    ("https://www.reddit.com/r/linuxmasterrace.rss" reddit)
    ("https://www.reddit.com/r/linuxquestions.rss" reddit)
    ("https://www.reddit.com/r/lisp.rss" reddit)
    ("https://www.reddit.com/r/lmms.rss" reddit)
    ("https://www.reddit.com/r/manim.rss" reddit)
    ("https://www.reddit.com/r/neovim.rss" reddit)
    ("https://www.reddit.com/r/netsecstudents.rss" reddit)
    ("https://www.reddit.com/r/networking.rss" reddit)
    ("https://www.reddit.com/r/orgmode.rss" reddit)
    ("https://www.reddit.com/r/programming.rss" reddit)
    ("https://www.reddit.com/r/programmingLanguages.rss" reddit)
    ("https://www.reddit.com/r/pytorch.rss" reddit)
    ("https://www.reddit.com/r/quantum.rss" reddit)
    ("https://www.reddit.com/r/qutebrowser.rss" reddit)
    ("https://www.reddit.com/r/ranger.rss" reddit)
    ("https://www.reddit.com/r/raspberry_pi.rss" reddit)
    ("https://www.reddit.com/r/selfhosted.rss" reddit)
    ("https://www.reddit.com/r/signal.rss" reddit)
    ("https://www.reddit.com/r/statistics.rss" reddit)
    ("https://www.reddit.com/r/stats.rss" reddit)
    ("https://www.reddit.com/r/suckless.rss" reddit)
    ("https://www.reddit.com/r/svg.rss" reddit)
    ("https://www.reddit.com/r/tails.rss" reddit)
    ("https://www.reddit.com/r/techsupport.rss" reddit)
    ("https://www.reddit.com/r/tutanota.rss" reddit)
    ("https://www.reddit.com/r/unix.rss" reddit)
    ("https://www.reddit.com/r/vim.rss" reddit)
    ("https://www.reddit.com/r/vimplugins.rss" reddit)
    ("https://www.reddit.com/r/visualization.rss" reddit)
    ("https://www.reddit.com/r/vscode.rss" reddit)
    ("https://www.reddit.com/r/zsh.rss" reddit)

  ))
